- name: CacheConfigHolder
    params:
      - name: name
        type: String
        nullable: false
      - name: managerPrefix
        type: String
        nullable: true
      - name: uriString
        type: String
        nullable: true
      - name: backupCount
        type: int
        nullable: false
      - name: asyncBackupCount
        type: int
        nullable: false
      - name: inMemoryFormat
        type: String
        nullable: false
      - name: evictionConfig
        type: EvictionConfigHolder
        nullable: false
      - name: wanReplicationRef
        type: WanReplicationRef
        nullable: true
      - name: keyClassName
        type: String
        nullable: false
      - name: valueClassName
        type: String
        nullable: false
      - name: cacheLoaderFactory
        type: Data
        nullable: true
      - name: cacheWriterFactory
        type: Data
        nullable: true
      - name: expiryPolicyFactory
        type: Data
        nullable: false
      - name: isReadThrough
        type: Boolean
        nullable: false
      - name: isWriteThrough
        type: Boolean
        nullable: false
      - name: isStoreByValue
        type: Boolean
        nullable: false
      - name: isManagementEnabled
        type: Boolean
        nullable: false
      - name: isStatisticsEnabled
        type: Boolean
        nullable: false
      - name: hotRestartConfig
        type: HotRestartConfig
        nullable: true
      - name: eventJournalConfig
        type: EventJournalConfig
        nullable: true
      - name: splitBrainProtectionName
        type: String
        nullable: true
      - name: listenerConfigurations
        type: List_CacheSimpleEntryListenerConfig
        nullable: true
      - name: mergePolicyConfig
        type: mergePolicy
        nullable: false
      - name: disablePerEntryInvalidationEvents
        type: Boolean
        nullable: false

