name: PR Builder

on:
  pull_request

jobs:
  pr-builder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.7

      - run: |
            pip3 install -r requirements.txt

      - run: |
            for lang in java cpp cs py ts; do
                ./generator.py --lang ${lang}
            done
